In [7]:
import pandas as pd
from typing import Tuple
import math
import numpy as np
from tqdm import tqdm

# Cleaning team_stats
This notebook provides a clean version of the raw teamstats.csv file.
If does the following:
1. Add a 'season' column
2. Filter for 'value' rows
3. Save to a new csv, `.data/{schedule_name}_cleaned.csv`

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
teamstats = pd.read_csv(f'teamstats.csv')
teamstats.head()

/var/folders/f3/w3vlb72x47z3vhjsm9s6jlxc0000gn/T/ipykernel_8044/1805963730.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,44,46,61,63,99,110) have mixed types. Specify dtype option on import or set low_memory=False.
  teamstats = pd.read_csv(f'teamstats.csv')

,gid,team,inn1,inn2,inn3,inn4,inn5,inn6,inn7,inn8,inn9,inn10,inn11,inn12,inn13,inn14,inn15,inn16,inn17,inn18,inn19,inn20,inn21,inn22,inn23,inn24,inn25,inn26,inn27,inn28,lob,mgr,stattype,b_pa,b_ab,b_r,b_h,b_d,b_t,b_hr,b_rbi,b_sh,b_sf,b_hbp,b_w,b_iw,b_k,b_sb,b_cs,b_gdp,b_xi,b_roe,p_ipouts,p_noout,p_bfp,p_h,p_d,p_t,p_hr,p_r,p_er,p_w,p_iw,p_k,p_hbp,p_wp,p_bk,p_sh,p_sf,p_sb,p_cs,p_pb,d_po,d_a,d_e,d_dp,d_tp,d_pb,d_wp,d_sb,d_cs,start_l1,start_l2,start_l3,start_l4,start_l5,start_l6,start_l7,start_l8,start_l9,start_f1,start_f2,start_f3,start_f4,start_f5,start_f6,start_f7,start_f8,start_f9,start_f10,date,number,site,vishome,opp,win,loss,tie,gametype,box,pbp
0,CIN189804150,CL4,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,tebep101,value,34.0,29.0,2.0,5.0,2.0,1.0,0.0,2.0,1.0,0.0,0.0,4.0,0.0,2.0,0.0,NaN,NaN,0.0,NaN,27.0,0.0,34.0,7.0,0.0,1.0,0.0,3.0,1.0,1.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,NaN,1.0,27.0,15.0,3.0,0.0,0.0,1.0,0.0,1.0,NaN,burkj101,mckee101,chilc101,wallb101,mcalj102,blakh101,tebep101,oconj104,younc102,younc102,oconj104,tebep101,chilc101,wallb101,mckee101,burkj101,mcalj102,blakh101,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
1,CIN189804150,CL4,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,tebep101,official,NaN,29.0,2.0,5.0,2.0,1.0,0.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,27.0,NaN,34.0,7.0,NaN,NaN,0.0,3.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,15.0,3.0,NaN,NaN,1.0,NaN,NaN,NaN,burkj101,mckee101,chilc101,wallb101,mcalj102,blakh101,tebep101,oconj104,younc102,younc102,oconj104,tebep101,chilc101,wallb101,mckee101,burkj101,mcalj102,blakh101,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
2,CIN189804150,CIN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,ewinb101,value,34.0,31.0,3.0,7.0,0.0,1.0,0.0,3.0,1.0,0.0,1.0,1.0,0.0,2.0,1.0,NaN,NaN,0.0,NaN,27.0,0.0,34.0,5.0,2.0,1.0,0.0,2.0,2.0,4.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,27.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN,mcfah102,smitm104,beckj103,milld105,mcphb101,corct101,irwic101,peith101,breit101,breit101,peith101,beckj103,mcphb101,irwic101,corct101,smitm104,mcfah102,milld105,NaN,18980415,0.0,CIN05,h,CL4,1,0,0,regular,y,NaN
3,CIN189804150,CIN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,ewinb101,official,NaN,31.0,3.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,27.0,NaN,34.0,5.0,NaN,NaN,0.0,2.0,NaN,4.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,14.0,2.0,NaN,NaN,0.0,NaN,NaN,NaN,mcfah102,smitm104,beckj103,milld105,mcphb101,corct101,irwic101,peith101,breit101,breit101,peith101,beckj103,mcphb101,irwic101,corct101,smitm104,mcfah102,milld105,NaN,18980415,0.0,CIN05,h,CL4,1,0,0,regular,y,NaN
4,LS3189804150,PIT,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,watkb101,value,38.0,36.0,3.0,15.0,1.0,1.0,1.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,27.0,0.0,42.0,13.0,0.0,1.0,0.0,10.0,8.0,3.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,27.0,15.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,paddd102,donop101,brods101,mccaj105,davih101,greyb101,ely-b101,schrp101,killf101,killf101,schrp101,davih101,paddd102,greyb101,ely-b101,mccaj105,brods101,donop101,NaN,18980415,0.0,LOU03,v,LS3,0,1,0,regular,y,NaN

## 1. Add 'season' column

In [10]:
teamstats['season'] = teamstats['date'].apply(lambda x: int(str(x)[:4]))
teamstats.head()

,gid,team,inn1,inn2,inn3,inn4,inn5,inn6,inn7,inn8,inn9,inn10,inn11,inn12,inn13,inn14,inn15,inn16,inn17,inn18,inn19,inn20,inn21,inn22,inn23,inn24,inn25,inn26,inn27,inn28,lob,mgr,stattype,b_pa,b_ab,b_r,b_h,b_d,b_t,b_hr,b_rbi,b_sh,b_sf,b_hbp,b_w,b_iw,b_k,b_sb,b_cs,b_gdp,b_xi,b_roe,p_ipouts,p_noout,p_bfp,p_h,p_d,p_t,p_hr,p_r,p_er,p_w,p_iw,p_k,p_hbp,p_wp,p_bk,p_sh,p_sf,p_sb,p_cs,p_pb,d_po,d_a,d_e,d_dp,d_tp,d_pb,d_wp,d_sb,d_cs,start_l1,start_l2,start_l3,start_l4,start_l5,start_l6,start_l7,start_l8,start_l9,start_f1,start_f2,start_f3,start_f4,start_f5,start_f6,start_f7,start_f8,start_f9,start_f10,date,number,site,vishome,opp,win,loss,tie,gametype,box,pbp,season
0,CIN189804150,CL4,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,tebep101,value,34.0,29.0,2.0,5.0,2.0,1.0,0.0,2.0,1.0,0.0,0.0,4.0,0.0,2.0,0.0,NaN,NaN,0.0,NaN,27.0,0.0,34.0,7.0,0.0,1.0,0.0,3.0,1.0,1.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,NaN,1.0,27.0,15.0,3.0,0.0,0.0,1.0,0.0,1.0,NaN,burkj101,mckee101,chilc101,wallb101,mcalj102,blakh101,tebep101,oconj104,younc102,younc102,oconj104,tebep101,chilc101,wallb101,mckee101,burkj101,mcalj102,blakh101,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
1,CIN189804150,CL4,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,tebep101,official,NaN,29.0,2.0,5.0,2.0,1.0,0.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,27.0,NaN,34.0,7.0,NaN,NaN,0.0,3.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,15.0,3.0,NaN,NaN,1.0,NaN,NaN,NaN,burkj101,mckee101,chilc101,wallb101,mcalj102,blakh101,tebep101,oconj104,younc102,younc102,oconj104,tebep101,chilc101,wallb101,mckee101,burkj101,mcalj102,blakh101,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
2,CIN189804150,CIN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,ewinb101,value,34.0,31.0,3.0,7.0,0.0,1.0,0.0,3.0,1.0,0.0,1.0,1.0,0.0,2.0,1.0,NaN,NaN,0.0,NaN,27.0,0.0,34.0,5.0,2.0,1.0,0.0,2.0,2.0,4.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,27.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN,mcfah102,smitm104,beckj103,milld105,mcphb101,corct101,irwic101,peith101,breit101,breit101,peith101,beckj103,mcphb101,irwic101,corct101,smitm104,mcfah102,milld105,NaN,18980415,0.0,CIN05,h,CL4,1,0,0,regular,y,NaN,1898
3,CIN189804150,CIN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,ewinb101,official,NaN,31.0,3.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,27.0,NaN,34.0,5.0,NaN,NaN,0.0,2.0,NaN,4.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,14.0,2.0,NaN,NaN,0.0,NaN,NaN,NaN,mcfah102,smitm104,beckj103,milld105,mcphb101,corct101,irwic101,peith101,breit101,breit101,peith101,beckj103,mcphb101,irwic101,corct101,smitm104,mcfah102,milld105,NaN,18980415,0.0,CIN05,h,CL4,1,0,0,regular,y,NaN,1898
4,LS3189804150,PIT,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,watkb101,value,38.0,36.0,3.0,15.0,1.0,1.0,1.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,27.0,0.0,42.0,13.0,0.0,1.0,0.0,10.0,8.0,3.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,27.0,15.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,paddd102,donop101,brods101,mccaj105,davih101,greyb101,ely-b101,schrp101,killf101,killf101,schrp101,davih101,paddd102,greyb101,ely-b101,mccaj105,brods101,donop101,NaN,18980415,0.0,LOU03,v,LS3,0,1,0,regular,y,NaN,1898

## 2. Filter for 'value' rows

In [11]:
teamstats = teamstats[teamstats['stattype'] == 'value']

## 2. Save to `.csv`

In [15]:
teamstats.to_csv(f'./teamstats_clean.csv', index=False)