In [1]:
import pandas as pd
from typing import Tuple
import math
import numpy as np
from tqdm import tqdm
from pathlib import Path

# Cleaning pitching
This notebook provides a clean version of the raw pitching.csv file.
If does the following:
1. Add a 'season' column
2. Save to a new csv, `.data/clean/pitching_cleaned.csv`

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv(Path.cwd() / "analysis" / "data" / "raw" / "pitching.csv")
df.head()

,gid,id,team,p_seq,stattype,p_ipouts,p_noout,p_bfp,p_h,p_d,p_t,p_hr,p_r,p_er,p_w,p_iw,p_k,p_hbp,p_wp,p_bk,p_sh,p_sf,p_sb,p_cs,p_pb,wp,lp,save,p_gs,p_gf,p_cg,date,number,site,vishome,opp,win,loss,tie,gametype,box,pbp
0,CIN189804150,younc102,CL4,1.0,value,27.0,0.0,34.0,7.0,0.0,1.0,0.0,3.0,1.0,1.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
1,CIN189804150,younc102,CL4,1.0,official,27.0,NaN,34.0,7.0,NaN,NaN,0.0,3.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
2,CIN189804150,breit101,CIN,1.0,value,27.0,0.0,34.0,5.0,2.0,1.0,0.0,2.0,2.0,4.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,18980415,0.0,CIN05,h,CL4,1,0,0,regular,y,NaN
3,LS3189804150,killf101,PIT,1.0,value,27.0,0.0,42.0,13.0,0.0,1.0,0.0,10.0,8.0,3.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,18980415,0.0,LOU03,v,LS3,0,1,0,regular,y,NaN
4,LS3189804150,cunnb103,LS3,1.0,value,27.0,0.0,38.0,15.0,1.0,1.0,1.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,18980415,0.0,LOU03,h,PIT,1,0,0,regular,y,NaN

## 1. Add 'season' column

In [4]:
df['season'] = df['date'].apply(lambda x: int(str(x)[:4]))
df.head()

,gid,id,team,p_seq,stattype,p_ipouts,p_noout,p_bfp,p_h,p_d,p_t,p_hr,p_r,p_er,p_w,p_iw,p_k,p_hbp,p_wp,p_bk,p_sh,p_sf,p_sb,p_cs,p_pb,wp,lp,save,p_gs,p_gf,p_cg,date,number,site,vishome,opp,win,loss,tie,gametype,box,pbp,season
0,CIN189804150,younc102,CL4,1.0,value,27.0,0.0,34.0,7.0,0.0,1.0,0.0,3.0,1.0,1.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
1,CIN189804150,younc102,CL4,1.0,official,27.0,NaN,34.0,7.0,NaN,NaN,0.0,3.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
2,CIN189804150,breit101,CIN,1.0,value,27.0,0.0,34.0,5.0,2.0,1.0,0.0,2.0,2.0,4.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,18980415,0.0,CIN05,h,CL4,1,0,0,regular,y,NaN,1898
3,LS3189804150,killf101,PIT,1.0,value,27.0,0.0,42.0,13.0,0.0,1.0,0.0,10.0,8.0,3.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,18980415,0.0,LOU03,v,LS3,0,1,0,regular,y,NaN,1898
4,LS3189804150,cunnb103,LS3,1.0,value,27.0,0.0,38.0,15.0,1.0,1.0,1.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,18980415,0.0,LOU03,h,PIT,1,0,0,regular,y,NaN,1898

## 2. Save to `.csv`

In [ ]:
df.to_csv(Path.cwd() / "analysis" / "data" / "clean" / "pitching_clean.csv", index=False)