In [1]:
import pandas as pd
from typing import Tuple
import math
import numpy as np
from tqdm import tqdm
from pathlib import Path

# Cleaning batting
This notebook provides a clean version of the raw batting.csv file.
If does the following:
1. Add a 'season' column
2. Save to a new csv, `.data/clean/batting_cleaned.csv`

In [2]:
pd.set_option('display.max_columns', None)

In [ ]:
batting = pd.read_csv(Path.cwd() / "analysis" / "data" / "raw" / "batting.csv")
batting.head()

/var/folders/f3/w3vlb72x47z3vhjsm9s6jlxc0000gn/T/ipykernel_22450/3555537178.py:1: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  batting = pd.read_csv(f'batting.csv')

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,b_d,b_t,b_hr,b_rbi,b_sh,b_sf,b_hbp,b_w,b_iw,b_k,b_sb,b_cs,b_gdp,b_xi,b_roe,dh,ph,pr,date,number,site,vishome,opp,win,loss,tie,gametype,box,pbp
0,CIN189804150,burkj101,CL4,1.0,1.0,value,4.0,4.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
1,CIN189804150,mckee101,CL4,2.0,1.0,value,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
2,CIN189804150,chilc101,CL4,3.0,1.0,value,4.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
3,CIN189804150,wallb101,CL4,4.0,1.0,value,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN
4,CIN189804150,mcalj102,CL4,5.0,1.0,value,4.0,3.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN

## 1. Add 'season' column

In [4]:
batting['season'] = batting['date'].apply(lambda x: int(str(x)[:4]))
batting.head()

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,b_d,b_t,b_hr,b_rbi,b_sh,b_sf,b_hbp,b_w,b_iw,b_k,b_sb,b_cs,b_gdp,b_xi,b_roe,dh,ph,pr,date,number,site,vishome,opp,win,loss,tie,gametype,box,pbp,season
0,CIN189804150,burkj101,CL4,1.0,1.0,value,4.0,4.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
1,CIN189804150,mckee101,CL4,2.0,1.0,value,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
2,CIN189804150,chilc101,CL4,3.0,1.0,value,4.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
3,CIN189804150,wallb101,CL4,4.0,1.0,value,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898
4,CIN189804150,mcalj102,CL4,5.0,1.0,value,4.0,3.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,18980415,0.0,CIN05,v,CIN,0,1,0,regular,y,NaN,1898

## 2. Save to `.csv`

In [ ]:
batting.to_csv(Path.cwd() / "analysis" / "data" / "clean" / "batting_clean.csv", index=False)