In [ ]:
from src.utils.generic_utils import load_all_games_csv, predict_lr
from src.utils.elo_tracker_utils import evaluate_elo_prob_func
import numpy as np

# Model vs 538

This will compare my best model to the 538 baseline, for the 2024 season.

## Get 2024 Season Games

In [105]:
games = load_all_games_csv('../data/gameinfo_cleaned.csv')
games = games[games['season']==2024]
games.head()

/Users/lancehendricks/Documents/College Coding/ML/Elo Ratings/analysis/src/utils/utils.py:27: DtypeWarning: Columns (10,11,13,17,19,21,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  all_games = pd.read_csv(filename)

,visteam,hometeam,site,date,number,starttime,daynight,innings,tiebreaker,usedh,...,homerestdays,visrestdays,homepitcherrgs,vispitcherrgs,hometeamrgs,visteamrgs,homepitcherminusteamrgs,vispitcherminusteamrgs,homelastkwinpct,vislastkwinpct
gid,,,,,,,,,,,,,,,,,,,,,
SDN202403200,LAN,SDN,SEO01,20240320,0.0,7:05PM,night,9.0,2.0,True,...,171.0,161.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN
LAN202403210,SDN,LAN,SEO01,20240321,0.0,7:05PM,night,9.0,2.0,True,...,1.0,1.0,39.0,39.0,54.9,53.9,-15.9,-14.9,1.0,0.0
ARI202403280,COL,ARI,PHO01,20240328,0.0,7:10PM,night,9.0,2.0,True,...,148.0,179.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN
BAL202403280,ANA,BAL,BAL12,20240328,0.0,3:05PM,day,9.0,2.0,True,...,170.0,179.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN
CHA202403280,DET,CHA,CHI12,20240328,0.0,3:10PM,day,9.0,2.0,True,...,179.0,179.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN

In [106]:
# Max rest days
games['visrestdays'] = games['visrestdays'].apply(lambda x: min(3,x))
games['homerestdays'] = games['homerestdays'].apply(lambda x: min(3,x))

In [107]:
# Take cube root of distance traveled
games['homedistancetraveled'] = games['homedistancetraveled']**(1/3)
games['visdistancetraveled'] = games['visdistancetraveled']**(1/3)

In [108]:
# Take square root of margin of victory
games['marginofvictory'] = np.sqrt(games['marginofvictory'])
games.head()

,visteam,hometeam,site,date,number,starttime,daynight,innings,tiebreaker,usedh,...,homerestdays,visrestdays,homepitcherrgs,vispitcherrgs,hometeamrgs,visteamrgs,homepitcherminusteamrgs,vispitcherminusteamrgs,homelastkwinpct,vislastkwinpct
gid,,,,,,,,,,,,,,,,,,,,,
SDN202403200,LAN,SDN,SEO01,20240320,0.0,7:05PM,night,9.0,2.0,True,...,3.0,3.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN
LAN202403210,SDN,LAN,SEO01,20240321,0.0,7:05PM,night,9.0,2.0,True,...,1.0,1.0,39.0,39.0,54.9,53.9,-15.9,-14.9,1.0,0.0
ARI202403280,COL,ARI,PHO01,20240328,0.0,7:10PM,night,9.0,2.0,True,...,3.0,3.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN
BAL202403280,ANA,BAL,BAL12,20240328,0.0,3:05PM,day,9.0,2.0,True,...,3.0,3.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN
CHA202403280,DET,CHA,CHI12,20240328,0.0,3:10PM,day,9.0,2.0,True,...,3.0,3.0,39.0,39.0,39.0,39.0,0.0,0.0,NaN,NaN

## Evaluate my Model

In [ ]:
w = np.array([[ 1.        ],
       [27.1440666 ],
       [ 4.81476328],
       [-0.30523283],
       [ 1.58004319]])

In [ ]:
bce, accuracy = evaluate_elo_prob_func(games, , K=3, use_margin_of_victory=True, skip_first_n=0)lambda home_elo, away_elo, game: predict_lr(home_elo, away_elo, game, w)
print(f"BCE: {bce}")
print(f"Accuracy: {accuracy}")

BCE: 0.6829313083151032
Accuracy: 0.5542071197411004

## Evaluate 538 Model

In [115]:
w_538 = np.array([[ 1.        ],
       [24 ],
       [ 2.3],
       [-0.31],
       [ 4.7]])

In [129]:
bce, accuracy = evaluate_elo_prob_func(games, lambda home_elo, away_elo, game: predict_lr(home_elo, away_elo, game, w_538), K=3, use_margin_of_victory=False, skip_first_n=0)
print(f"538 BCE: {bce}")
print(f"538 Accuracy: {accuracy}")

538 BCE: 0.6888037824221744
538 Accuracy: 0.5469255663430421